### ISSUE TITLE
is it possible to make voip calls?

### ISSUE THREAD

**Issue by kushaldias** [hoxfon/react-native-twilio-programmable-voice#102]
i want to make a call to a voip contact. is this possible? 
ev - i have a user with a token which is granted with a unique name. i want to make a call to this user.

TwilioVoice.connect('+5436464545')
i want above to be like TwilioVoice.connect('kushal')

is this possible? if so, how?

**Comment by jdegger** [comment]
Hi, since a long time has passed I will be closing this issue. Read our repository update in #158. I invite you to reopen this issue when you still have problems so we can debug the problems together.
