### ISSUE TITLE
Crash on incoming GCM notification due to dependency conflict

### ISSUE THREAD

**Issue by BTBurke** [hoxfon/react-native-twilio-programmable-voice#11]
What version of React Native are you running?  0.42.0

What version of react-native-twilio-programmable-voice are you running? 0.4.0

What device are you using? (e.g iOS9 emulator, Android 6 device)?  Android emulator

Is your app running in foreground, background or not running? Foreground

Is there any relevant message in the log?  Crashes when receiving GCM notifications during an incoming call due to a version conflict between `play-services-gcm` and `firebase`.   Following the example in the README and using version `10.2.0` will cause a conflict when firebase libs used in this library are a different version.  

Stack trace:

```
03-14 22:06:04.534  6015  6015 D AndroidRuntime: Shutting down VM
03-14 22:06:04.535  6015  6015 E AndroidRuntime: FATAL EXCEPTION: main
03-14 22:06:04.535  6015  6015 E AndroidRuntime: Process: com.twilio.voice.quickstart, PID: 6015
03-14 22:06:04.535  6015  6015 E AndroidRuntime: java.lang.NoSuchMethodError: No static method zzaaj()Lcom/google/firebase/iid/zzg; in class Lcom/google/firebase/iid/zzg; or its super classes (declaration of 'com.google.firebase.iid.zzg' appears in /data/app/com.twilio.voice.quickstart-1/base.apk)
03-14 22:06:04.535  6015  6015 E AndroidRuntime: 	at com.google.firebase.messaging.FirebaseMessagingService.zzF(Unknown Source)
03-14 22:06:04.535  6015  6015 E AndroidRuntime: 	at com.google.firebase.iid.zzb.onStartCommand(Unknown Source)
03-14 22:06:04.535  6015  6015 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3010)
03-14 22:06:04.535  6015  6015 E AndroidRuntime: 	at android.app.ActivityThread.-wrap17(ActivityThread.java)
03-14 22:06:04.535  6015  6015 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1442)
03-14 22:06:04.535  6015  6015 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-14 22:06:04.535  6015  6015 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
03-14 22:06:04.535  6015  6015 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
03-14 22:06:04.535  6015  6015 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-14 22:06:04.535  6015  6015 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-14 22:06:04.535  6015  6015 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

This is fixed by setting `play-services-gcm` to the [same minor version number as used in the library](https://github.com/hoxfon/react-native-twilio-programmable-voice/blob/master/android/build.gradle#L48).

```
    compile ('com.google.android.gms:play-services-gcm:10.0.+') {
        force = true;
    }
```

**Comment by fabriziomoscon** [comment]
@BTBurke thanks for reporting.
I will amend the README to advise about this issue (or you can do it if you wish to open a PR)
Perhaps having the library using `10.+` rather than `10.0.+` could allow it, but I am not too keen on referring to a broad range of library versions.
I am not sure why your log message starts with `Process: com.twilio.voice.quickstart ...` that should not be the case, do you know why? Is your app including both this library and the Twilio native one?

**Comment by BTBurke** [comment]
I was only using the the react-native version but I was following the Twilio quickstart example closely and I had set up my GCM notifications to align with `com.twilio.voice.quickstart`.  I was also using the example python server they reference in the quickstart.   I renamed my package to that to work with my `google-services.json`.  I'm not sure if that is required, but I was getting some compilation errors because the package name was different.

It took me quite a bit of trial and error to get everything to compile and work.  I'll go ahead and fork it and update the README with a bit more information to get people pointed in the right direction.

**Comment by fabriziomoscon** [comment]
You can use any server you want, that won't impact the client.
The package name of you App must match the one inside `google-services.json`, but the GCM service in the manifest must be
```
<service android:name="com.hoxfon.react.TwilioVoice.gcm.GCMRegistrationService" />
```
otherwise the library's code will not be used to handle call notifications.

At the end you should not have any trace of `com.twilio.voice.quickstart`, because that package should not get included and compiled
Does it make sense?

**Comment by BTBurke** [comment]
Makes sense.  Let me take a look at mine and make sure it's set up correctly.  I'm getting GCM notifications and able to accept the call so I believe it's working.  Before changing the `play-services-gcm` version the app was crashing on each incoming notification.
