### ISSUE TITLE
Android Notifications with React Native Firebase

### ISSUE THREAD

**Issue by jheyer159** [hoxfon/react-native-twilio-programmable-voice#110]
Has anyone used this library with React Native Firebase and specifically the notifications?  Both libraries override the onMessageReceived function - as per the Firebase instructions.

When I activate both libraries in the Android Manifest the call no longer works.  I'm assuming this is because both libraries are 'attached' to 

`<action android:name="com.google.firebase.MESSAGING_EVENT" />`

And they interfere with each other.  My understanding is that both libraries can't use the same action in the intent-filter. 

How do we remedy this? Does it require java to route the notifications to their respective libraries, so only one intent-filter is setup for that action, then call the libraries respectively?

Can it be handled with the android manifest, or am I way off base?

Thanks for reading.

Did you follow all the instructions as specified in the Twilio Quickstart repositories? **Yes**
What version of React Native are you running? **0.54**
What version of react-native-twilio-programmable-voice are you running? **3.18.1**
What device are you using? (e.g iOS10 simulator, Android 7 device)? **Android device**
Is your app running in foreground, background or not running? **All of the above**

**Comment by fabriziomoscon** [comment]
I would also be interested to know how to set up the app so that multiple services can handle notifications.

**Comment by turingbombe** [comment]
I am facing the same problem. I don't have much android dev experience but was thinking of either:
A.) creating a "router" to send the messages to the appropriate place.
B.) somehow associate different Firebase apps with their respective services.

Do either of these sound like viable approaches?

**Comment by jheyer159** [comment]
[I'm currently testing this setup.](https://github.com/jheyer159/react-native-twilio-programmable-voice/commit/47ddd875de6242a8aa63493294245d61bed77197)

You can see this code was added to `RNTwilioVoice/fcm/VoiceFirebaseMessagingService.java` inside the `if (remoteMessage.getNotification() != null)` block.

`
Intent notificationEvent = new Intent("notifications-remote-notification");
notificationEvent.putExtra("notification", remoteMessage);
// Broadcast it to the (foreground) RN Application
LocalBroadcastManager.getInstance(this).sendBroadcast(notificationEvent);
`

In the AndroidManifest I only hooked up this Library to avoid interference with multiple intent filters. This seems to be the least intrusive method I've tried so far.

Now I'm working to get the icons to render correctly, but notifications is a big win!

**Comment by turingbombe** [comment]
Nice thanks @jheyer159 that was a huge help
