### ISSUE TITLE
TwilioVoice.disconnect() does not play disconnect tone

### ISSUE THREAD

**Issue by gentleShark** [hoxfon/react-native-twilio-programmable-voice#112]
On Android (and possibly iOS also though I haven't tested) TwilioVoice.disconnect() successfully terminates the call play but does not play an audio tone to convey to the user that the call has been terminated.

**Comment by gentleShark** [comment]
the twilio java quickstart implements this by playing disconnect.wav in the raw resources directory but I didn't have much luck importing that file, modifying SoundPoolManager.java considerably, and modifying the TwilioVoiceManager.java disconnect function. my react native app still works but no dissconnect.wav sound

**Comment by gentleShark** [comment]
I just created a pull request for this issue: #113

**Comment by jdegger** [comment]
I will be closing this issue so we can continue the discussion on #133
