### ISSUE TITLE
How to show call duration on the twillio call screen?

### ISSUE THREAD

**Issue by smitthakkar1** [hoxfon/react-native-twilio-programmable-voice#115]
So, I want to show call duration during the call. I tried using `setInterval` every second and it works great on Android but on iOS, when someone lifts their phone to the ear, phone screen goes black (which is fine and expected) but the problem is, it stops increasing that call duration timer.

I try debugging the component and figure out that component stops rendering when the screen goes black. I am changing state every second by increasing timer and it re-renders the screen on android fine but not on iOS. I was wondering if there is any way to access the call duration real-time using this package or any other way to resolve this issue?

Also, on both platform, if I switch the app to the background (during the call), I ger this notification bar which also reflects the call duration and surprisingly that call duration is correct. If someone can point out how to access that would be really helpful to me.

Did you follow all the instructions as specified in the Twilio Quickstart repositories?
What version of React Native are you running?
0.57.7
What version of react-native-twilio-programmable-voice are you running?
3.21.1
What device are you using? (e.g iOS10 simulator, Android 7 device)?
iPhone 7, iPhone X
Is your app running in foreground, background or not running?
Running in foreground
Is there any relevant message in the log?
nope
If using iOS, which pod version are you using?
1.5.3
Step to reproduce
Lift the phone during call which will prevent re-rendering the call screen.

**Comment by smitthakkar1** [comment]
I solved this problem using react's state. I did `setState` when call get started and each second I was re-rendering the screen using `setTimeout` and showing the difference between currentTime and the time in state.

**Comment by SalmanMehmood** [comment]
When I dial a call to any number an event fired "connectionDidConnect" , when the user receives call no event fired, so how can I run call timer?

**Comment by Serge-purr** [comment]
First of all: thank you very-very-very much for your work.
I've got same question as @SalmanMehmood asked. "callStateRinging" event returns only call_sid. 
From console: 
`callStateRinging data {call_sid: "CA79da86a73d9d7ae501f729066ce4b"}`
`connectionDidConnect data {call_state: "CONNECTED", call_sid: "CA79da86a73d9d7ae501f729066ce4b"}`
connectionDidConnect returns "connected" always. Docs says that we can get  "call_state: 'CONNECTED' | 'ACCEPTED' | 'CONNECTING' | 'RINGING' | 'DISCONNECTED' | 'CANCELLED'". So, how can i get it ('accepted' call_state)? Thanks)
