### ISSUE TITLE
TwilioVoice.connect doesn't work

### ISSUE THREAD

**Issue by JosephMulder** [hoxfon/react-native-twilio-programmable-voice#117]
When I run TwilioVoice.connect I don't get any errors in react-native, but I do get this in android studio. 
D/RNTwilioVoice: sendEvent connectionDidDisconnect params { NativeMap: {"call_to":null,"call_state":"DISCONNECTED","call_sid":null,"call_from":null,"err":"TwiML application not found"} }

The even listener just said the device was ready so i'm not sure why it wouldn't work.

**Comment by MssMaster** [comment]
@JosephMulder, I am getting exactly the same issue. Please give me a solution to this problem.

**Comment by tragicmj** [comment]
How is this issue resolved @JosephMulder  @MssMaster ??
