### ISSUE TITLE
Screen shut off when making a call 

### ISSUE THREAD

**Issue by whoops1122** [hoxfon/react-native-twilio-programmable-voice#119]
Hello All,

We are facing an issue with the demo, after clicking to make the call, the screen shut off completely but the call will go through.  this issue only happens on our device running with android 6.0.1

attached the error log here, (cause its too long)

[errorfile1.txt](https://github.com/hoxfon/react-native-twilio-programmable-voice/files/2928011/errorfile1.txt)

**Comment by fangzhzh** [comment]
According to the log
```
03-04 10:26:08.853 3475-3556/com.reactnativetwilioexampleapp D/RNTwilioVoice: initProximitySensorEventListener()
03-04 10:26:08.854 3475-3556/com.reactnativetwilioexampleapp D/RNTwilioVoice: register proximity listener
03-04 10:26:08.861 3475-3475/com.reactnativetwilioexampleapp D/RNTwilioVoice: turnScreenOff()
03-04 10:26:08.862 3475-3556/com.reactnativetwilioexampleapp D/RNTwilioVoice: startWiredHeadsetEvent()
03-04 10:26:08.865 3475-3475/com.reactnativetwilioexampleapp D/RNTwilioVoice: sendEvent proximity params { NativeMap: {"isNear":true} }
```

you phone thinks something is near the screen, so it turns your screen off.

I guess that It also turn the screen off when you do gsm call.

**Comment by whoops1122** [comment]
Oh I see what you meant, the phone thinks that my face is right next to the ear so it turn the screen off....well that resolve the issue....
