### ISSUE TITLE
iOS connectionDidConnect does not fire ACCEPTED event

### ISSUE THREAD

**Issue by langan** [hoxfon/react-native-twilio-programmable-voice#121]
Did you follow all the instructions as specified in the Twilio Quickstart repositories?
**Yes**
What version of React Native are you running?
**16.8.3**
What version of react-native-twilio-programmable-voice are you running?
**3.21.1**
What device are you using? (e.g iOS10 simulator, Android 7 device)?
**iPhone 5s & iOS Simulator**
Is your app running in foreground, background or not running?
**foreground**
Is there any relevant message in the log?
**No**
If using iOS, which pod version are you using?
**2.0.7**

Step to reproduce

1. Make a call from iOS device to another iOS device using `TwilioVoice.connect` 
2. Answer using CallKit
3. Device making the call does not get any `ACCEPTED` event 

Advanced:
Have you tried adding break point using AndroidStudio or XCode and analyse the logs?
**No**
can share a project with issue?
**No**
Did you try to reinstall the pods completely?
**Yes**

**Comment by fabriziomoscon** [comment]
Please test #144

**Comment by jdegger** [comment]
Hi, since a long time has passed I will be closing this issue. Read our repository update in #158. I invite you to reopen this issue when you still have problems so we can debug the problems together.
