### ISSUE TITLE
Record Call Locally

### ISSUE THREAD

**Issue by jacob-cross99** [hoxfon/react-native-twilio-programmable-voice#122]
I'd like to record the inbound audio input so I can process NLP locally without paying twilio. Is there a way to access the audio input?

**Comment by jdegger** [comment]
I dont think this is possible, at least not on iOS and maybe with some hacky manner in Android. At this moment, this would be outside the scope of what we're trying to achieve with this repo.

Since a long time has passed I will be closing this issue. Read our repository update in #158.
