### ISSUE TITLE
Twilio device access token showing registration failed

### ISSUE THREAD

**Issue by alikazmi2000** [hoxfon/react-native-twilio-programmable-voice#126]
I have implemented the code, but as i pass a valid access token it always shows Registration failed error

**Comment by nabinem** [comment]
i am getting same error

**Comment by alikazmi2000** [comment]
I have solved the error. I only changed the device token code and submitted
the push credentials in it

**Comment by fabriziomoscon** [comment]
Any chance that this relates to iOS 13?
https://github.com/twilio/voice-quickstart-swift/issues/255

**Comment by jdegger** [comment]
Hi, since a long time has passed I will be closing this issue. Read our repository update in #158. I invite you to reopen this issue when you still have problems so we can debug the problems together.
