### ISSUE TITLE
Upgrade Twilio Voice SDKs to 4.x

### ISSUE THREAD

**Issue by pinstripe-potatohead** [hoxfon/react-native-twilio-programmable-voice#127]
Twilio Voice Android/iOS SDK documentation [here](twilio.com/docs/voice/voip-sdk/android) says:

> 4.x is the latest release of Programmable Voice SDKs. If you are using an older version, Twilio recommends upgrading to 4.x as soon as possible.

> Support for 3.x will cease Jul 1st, 2020.This branch will only receive fixes for critical issues. Check this guide when planning your migration to 4.x.

> Support for 2.x will cease Jan 1st, 2020.This branch will only receive fixes for critical issues. Check this guide when planning your migration to 3.x.

This library still uses v2.x, which will lose support in 3 months. Could someone upgrade it to the newest version?

**Comment by TheRohitSharma** [comment]
It should be 5.0 now. 

https://github.com/twilio/twilio-voice-ios/releases/tag/5.0.0

**Comment by patweb99** [comment]
Has anyone started on this?

**Comment by jdegger** [comment]
We have been using a different package to solve this issue (https://github.com/danielsGit/react-native-twilio-voice-module) however, this package does not support CallKit.

Does anybody have any progress on this, the deadline is near.

**Comment by fabriziomoscon** [comment]
@jdegger could you please try this? 
https://github.com/hoxfon/react-native-twilio-programmable-voice/pull/130

**Comment by jdegger** [comment]
@fabriziomoscon we did, it seemed to work, however that fork is Android changes only, so we still have the same problem for iOS

**Comment by fabriziomoscon** [comment]
This library version `3.21.3` is not compatible with iOS 13.
Twilio 2.0 libraries iOS/Android will not be supported next year and also is not compatible with iOS 13.
We will need to integrate the new iOS code and follow this migration guide:
https://github.com/twilio/twilio-voice-ios/blob/Releases/iOS-13-Migration-Guide.md

**Comment by fecabianchi** [comment]
@fabriziomoscon @jdegger is migration to sdk 5 (iOS and Android) happening? if so, is there a roadmap for what has already been done?

**Comment by fabriziomoscon** [comment]
I am currently working on #144 which despite the name contains a working Android SDK v4 and will contain iOS SDK v4

**Comment by fabriziomoscon** [comment]
please test #144

**Comment by jdegger** [comment]
This has been implemented. Read more here: #158
