### ISSUE TITLE
Deprecated "rnpm" config

### ISSUE THREAD

**Issue by josaric** [hoxfon/react-native-twilio-programmable-voice#131]
When running command:
`react-native link`
I get 
```
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-twilio-programmable-voice: https://github.com/hoxfon/react-native-twilio-programmable-voice
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
```

"react": "16.9.0",
"react-native": "0.61.2",

**Comment by enaluz** [comment]
Just made a PR ([#132](https://github.com/hoxfon/react-native-twilio-programmable-voice/pull/132)) with a fix for this. The maintainers for this library might take a while to fix this, but I would recommend using [patch-package](https://www.npmjs.com/package/patch-package) as a temporary fix.

**Comment by fabriziomoscon** [comment]
The latest version on npm should fix this
