### ISSUE TITLE
Not supported in react-native 0.61.4

### ISSUE THREAD

**Issue by ahsanjamilarkhitech** [hoxfon/react-native-twilio-programmable-voice#133]
Please include the following information for better support

The more context you provide around this issue the faster the community can help you

Did you follow all the instructions as specified in the Twilio Quickstart repositories?
What version of React Native are you running?
What version of react-native-twilio-programmable-voice are you running?
What device are you using? (e.g iOS10 simulator, Android 7 device)?
Is your app running in foreground, background or not running?
Is there any relevant message in the log?
If using iOS, which pod version are you using?

Step to reproduce

Advanced:
Have you tried adding break point using AndroidStudio or XCode and analyse the logs?
can share a project with issue?
Did you try to reinstall the pods completely?

**Comment by fabriziomoscon** [comment]
@ahsanjamilarkhitech please could you check if branch `feat/v4` works?
You need to use this command
`yarn add https://github.com/hoxfon/react-native-twilio-programmable-voice#feat/v4`

**Comment by aniravi24** [comment]
We're using react-native 0.61.5 and the current code works in our use case. Do you have more info on what is breaking for you?

**Comment by n-nitchevski** [comment]
@aniravi24 @fabriziomoscon 
Hi friends.
I hope to know if that supports iOS 13 devices.
Because to support that, we need to use iOS SDK version 5.x.
I'm having an issue after accept.
The call ringed successfully. And I press the accept button.
Then nothing happens. It still rings and no audio call started.

**Comment by fabriziomoscon** [comment]
I personally haven't tried react native 0.61, still upgrading my app to 0.60.
However by what I know from all the latest PR and comments is that there is a general feeling to work together to achieve that soon, in compatibility with everyone's involved other commitments.

**Comment by jdegger** [comment]
The newest version of this plugin works great on the newest RN.

Since a long time has passed I will be closing this issue. Read our repository update in #158. I invite you to reopen this issue when you still have problems so we can debug the problems together.
