### ISSUE TITLE
Will this library be maintained regularly?

### ISSUE THREAD

**Issue by enaluz** [hoxfon/react-native-twilio-programmable-voice#134]
Hi all! At first, I planned on just messaging @fabriziomoscon and any other official maintainers individually to ask this question. However, I instead decided to make a Github issue for this topic instead since I thought it would be best to have a conversation about this that everyone can participate in and for people reading this further into the future, a quick reference for the state of this library.

This library has been a key part of the product my cofounder @aniravi24 and I are working on (won't self-promote here, but feel free to ask if you're curious 😉). Although we've had our challenges with it, it has been incredibly valuable to us. Thank you to every contributor! 

Since this library is core to our product, it isn't maintained heavily, and the fact that Twilio recommends upgrading from iOS SDK versions below version 5.x (see screenshot), we thought we should ask the community which direction this library should go in.

![image](https://user-images.githubusercontent.com/26469879/70189310-33f57180-16b0-11ea-93e5-b50cb5e8d03f.png)

We're unsure if the maintainers of this library plan to continue work on this into the future, but if not, Ani and I plan to eventually fork this library and maintain it ourselves regularly along with any volunteers (which would be very helpful since neither of us are super experienced yet in native mobile development).

Would love to turn this into a conversation with anybody about best steps moving forward. Just hoping to clear the fog a bit here. Thank you to everyone and shoutout to @fabriziomoscon for merging some PRs a few hours ago.

**Comment by fabriziomoscon** [comment]
Hi, thanks for the message.
I personally run a side business based on this library, so it's in my interest not to miss Twilio updates and keep this project alive. However I tend to prioritise the work needed based on my needs.
Any help in maintaining this project is welcomed, since I can only work in this project in evenings and weekends.

If you agree, I will add you two as maintainers.

**Comment by fabriziomoscon** [comment]
By looking to the latest PRs and the comments I read lately I would like to ask to the following people:
@Pagebakers @gitstud @aniravi24 @enaluz @jdegger @nSimonFR 
who has the time, passion and interest to help me maintaining the library.
Please answer by Monday.

**Comment by jdegger** [comment]
@fabriziomoscon We are available for testing purposes and are willing to review PRs, however we do not have time to write any code at the moment.

**Comment by Pagebakers** [comment]
Unfortunately I don't have the resources to commit to maintaining, but I'm happy to make the occasional PR when possible.

Can't we get some help from Twilio? I can't believe they haven't made an official React Native package yet.

**Comment by fabriziomoscon** [comment]
From Twilio side could please @kbagchiGWC @idelgado @bchen-twilio could you give us a flavour of Twilio's appetite for maintaining this library?

**Comment by enaluz** [comment]
Sorry for the late response! Although @aniravi24 I aren't native developers (currently learning a bit here and there) we'd love to be helpful wherever we can with approving PRs and making the occasional PR when we see fit.  As long as we're working on our current product, we're vested in this library. In short, please make us collaborators.

**Comment by gitstud** [comment]
@fabriziomoscon I also feel a long term tie to this project, I'm going to be working with this library a lot more in a couple months time and would be happy to help keep it in shape, missed my opportunity to test out your branch this weekend so forgive me for that

**Comment by jdegger** [comment]
This discussion has been moved to #158 and gives an update on the maintenance status of this repo.
