### ISSUE TITLE
[Feature] Add ability to unregister the Twilio VoIP notification

### ISSUE THREAD

**Issue by lonnylot** [hoxfon/react-native-twilio-programmable-voice#140]
We currently register tokens with Twilio, but we have no way of unregistering them.

I propose a new JS method `TwilioVoice.unregister(accessToken)` that will call [[TwilioVoice unregisterWithAccessToken:deviceToken:completion:]](https://twilio.github.io/twilio-voice-ios/docs/latest/Classes/TwilioVoice.html#//api/name/unregisterWithAccessToken:deviceToken:completion:)

**Comment by TheRohitSharma** [comment]
I'm not sure that's accurate: https://github.com/hoxfon/react-native-twilio-programmable-voice/blob/master/index.js#L98

**Comment by lonnylot** [comment]
Good find. The README needs to be updated.
