### ISSUE TITLE
Didn't find class "com.twilio.voice.impl.session.CredentialInfo

### ISSUE THREAD

**Issue by ektasahu027** [hoxfon/react-native-twilio-programmable-voice#147]
When we call  TwilioVoice.connect(params); then I got this error.

![Screenshot 1399-01-01 at 15 41 22](https://user-images.githubusercontent.com/41745899/77154236-4f4e8600-6ac1-11ea-94ec-c3bdca769d4d.png)

Please help thank you.

**Comment by jdegger** [comment]
Hi, since a long time has passed I will be closing this issue. Read our repository update in #158. I invite you to reopen this issue when you still have problems so we can debug the problems together.
