### ISSUE TITLE
iOS Initial

### ISSUE THREAD

**Issue by jrperson** [hoxfon/react-native-twilio-programmable-voice#15]
I have Twilio Programmable Voice working perfectly within my own React Native app for iOS.  As I intend to now move to Android, I thought I would try to pull my code over to be included in this library to help someone else out.

I built the functionality outside of this library, so I pulled out the relevant bits from my own project and put it in my fork.  I haven't tested it from within the library yet, but the structure is all there that I used.  My biggest reservation is the linking of the Twilio library that is pulled in through the Podfile as I haven't tested it from within the library yet.

I utilized CallKit as it is super easy and much more integrated on iOS than manually handling calls.  Because of this, my implementation is missing manual calls for "accept", "reject", and "ignore."

If you want the PR, just let me know.  If someone wants to test, that would be appreciated as well as I don't have the time for that currently.

**Comment by sprice** [comment]
The README includes `Just open an issue or provide a PR. Everybody is welcome to contribute.`

I'd say go ahead an open a PR. This will be an amazing addition!

**Comment by jrperson** [comment]
I saw that clearly, but I didn't want to provide a PR on untested code and possibly derail someone else's efforts.  I pulled it out of my working project and into this library but I haven't tested it at all from within the library.
