### ISSUE TITLE
Twilio device ready is not giving any callbacks

### ISSUE THREAD

**Issue by pruthvirajkarur** [hoxfon/react-native-twilio-programmable-voice#155]
Hi I am trying to implement twilio for voice calls in my react native project.

I have successfully installed the npm
and when i do initWithToken i am getting success
 const success = await TwilioVoice.initWithToken("twilio token is sent here");

But i am not able to receive any call backs in the listners.

      TwilioVoice.addEventListener('deviceReady', () => {
          console.log('deviceReady ===========');
     });

I am not able to proceed further without getting any events for the listners.

My applicaiton is in foreground and i tries in both android and ios

Below are the verisons used
"react-native-twilio-programmable-voice": "^3.21.3
pod used   pod 'TwilioVoice', '~> 2.0.0' for ios
react-native-cli: 2.0.1
react-native: 0.62.2

**Comment by jdegger** [comment]
Hi, since a long time has passed I will be closing this issue. Read our repository update in #158. I invite you to reopen this issue when you still have problems so we can debug the problems together.
