### ISSUE TITLE
Twilio Pragammable sdk needs to be updated for ios 13 and 14

### ISSUE THREAD

**Issue by pruthvirajkarur** [hoxfon/react-native-twilio-programmable-voice#156]
![WhatsApp Image 2020-09-25 at 1 22 37 PM](https://user-images.githubusercontent.com/20319181/94243073-8d2adc00-ff34-11ea-96e1-e65aab46fb34.jpeg)

Call feature stopped working after upgrading to  ios14. Please suggest how to proceed.

[https://www.twilio.com/docs/voice/voip-sdk/ios](url)

**Comment by jdegger** [comment]
Proceed by migrating to the open PR branch here.
https://github.com/hoxfon/react-native-twilio-programmable-voice/pull/144

There are known limitations though, read the comments to see how to proceed.

**Comment by Daavidaviid** [comment]
> Proceed by migrating to the open PR branch here.
> #144
> 
> There are known limitations though, read the comments to see how to proceed.

I used that branch and it’s working nicely with outgoing calls. But the issues arise when I try receiving one. It works when the app is in the foreground but the app crashes when the app is in the background with the following message according to Crashlytics.

>Killing app because it never posted an incoming call to the system after receiving a PushKit VoIP push callback.

Anyone encountered this issue ?

**Comment by jdegger** [comment]
@Daavidaviid yes thats a common new problem everyone on ios 14 is facing. The solution is to implement react native callkeep in combination with this plugin. Unfortunately we have not completed our integration for iOS yet, but for Android it's working perfectly.

There are multiple comments describing this process in the #144 thread, search for 'callkeep' in the comments there and you will read a lot about it.

**Comment by Daavidaviid** [comment]
Thanks for your answer.
Well according to this post : https://github.com/twilio/voice-quickstart-ios/issues/308#issuecomment-625031633 it sounds like one has to call `initWithAccessToken` as soon as possible. So I'm gonna try modify that, otherwise I'll look into Callkeep.

In the official Quickstart for iOS, it seems to be working fine as is. I'll keep you updated

**Comment by Daavidaviid** [comment]
Well, I'm happily surprised, that was that.
I wasn't calling the `TwilioVoice.initWithToken()` method early enough. And that was causing an issue as mentionned in the post I referenced in my previous post.
So now what I do is call `initWithToken` at launch with a locally stored access token first, and I'm fetching an access token at the same time (that I save locally right after).

**Comment by jdegger** [comment]
Hi @Daavidaviid are you problems resolved? If you are still encountering problems let me know. Closing this issue for now 👍

**Comment by Daavidaviid** [comment]
Sounds like everything is working fine on our side.
We are currently using the branch that was merged recently with the latest pods from Twilio `pod 'TwilioVoice', '~> 5.5.1'`

We can receive and make calls without any issue on iOS 14. So it's great.

**Comment by jdegger** [comment]
Thanks for the update @Daavidaviid 👍 you basically helped us testing TwilioVoice 5.5.1 for iOS.
