### ISSUE TITLE
connectionDidConnect does not trigger an event in both android and ios

### ISSUE THREAD

**Issue by Samsritha1596** [hoxfon/react-native-twilio-programmable-voice#162]
Please include the following information for better support

The more context you provide around this issue the faster the community can help you

Did you follow all the instructions as specified in the Twilio Quickstart repositories? Yes
What version of React Native are you running? 0.61.5
What version of react-native-twilio-programmable-voice are you running? 3.21.3
What device are you using? (e.g iOS10 simulator, Android 7 device)? Ios 13 , android 10
Is your app running in foreground, background or not running? Foreground
Is there any relevant message in the log?
If using iOS, which pod version are you using?
Yes
Step to reproduce

Advanced:
Have you tried adding break point using AndroidStudio or XCode and analyse the logs? Yes
can share a project with issue?
Did you try to reinstall the pods completely?
Yes

**Comment by jdegger** [comment]
It seems like you're not on the newest version of this plugin. Can you please upgrade and try again? If you still encounter the problem please feel free to reopen this issue.

Also include code examples of what you're doing. Based on what you provided now, we can not help you I'm sorry.

**Comment by Samsritha1596** [comment]
I have upgraded the new version of this plugin. When user receives the call no event fired , How to get call "Accepted" status 

  TwilioVoice.addEventListener('connectionDidConnect', function(data) {
              console.log('connectionDidConnect status',data);
   })

**Comment by jdegger** [comment]
Where are you accepting the call. In your own interface?

**Comment by Samsritha1596** [comment]
In normal voice call

**Comment by jdegger** [comment]
Sorry your elaboration needs to be more elaborate.

**Comment by Samsritha1596** [comment]
User will accept the call like normal phone call.. (App to phone call )

**Comment by tragicmj** [comment]
Any update on this?
