### ISSUE TITLE
Call not coming when app is in background in iOS

### ISSUE THREAD

**Issue by suny2talk** [hoxfon/react-native-twilio-programmable-voice#165]
I have used latest twilio npm, but not get the call in background app state in latest iOS upper 13 version..

**Comment by jdegger** [comment]
Sorry, you issue is missing code, examples, configuration, versions etc. We can not help you this way.

**Comment by suny2talk** [comment]
I have used TwilioVoice (5.2.1) and RNTwilioVoice (4.1.0)..My react native version is "react-native": "0.63.3",..
Received call when app is in foreground, but do not get call when the is in background..
