### ISSUE TITLE
Incoming call not working for me

### ISSUE THREAD

**Issue by ErfanOrangetoolz** [hoxfon/react-native-twilio-programmable-voice#166]
I am trying to implement this package with incoming and outgoing call in react native app.
I finished the outgoing call.
But can not sync with incoming call with my app from twilio.
when I made a call from skype to a twilio number, i was ringing but call not showing in my app. I think i am missing some point and i can not trace it. please help me in this scenario for incoming call

**Comment by jdegger** [comment]
Please post code examples, configurations, versions. We can not help you without knowing what you are doing.

**Comment by ErfanOrangetoolz** [comment]
in landing page, App.js
in componentDidMount, I added this only with other listeners
      TwilioVoice.addEventListener('deviceDidReceiveIncoming', function(data) {
            TwilioVoice.accept();
            console.log('deviceDidReceiveIncoming'+data)
            alert("incoming call");
        })


"react-native-twilio-programmable-voice": "^3.21.3",
"react": "16.3.1",
"react-native": "^0.59.5",


ext {
buildToolsVersion = "28.0.3"
minSdkVersion = 16
compileSdkVersion = 28
targetSdkVersion = 28
supportLibVersion = "28.0.0"
}

anything else?

**Comment by jdegger** [comment]
make sure your token flow is correct, sorry based on the information you post here, it's just not sufficient to say something which can help you

**Comment by ErfanOrangetoolz** [comment]
Can you give me your email plz. I will share my dummy project with you

**Comment by Samsritha1596** [comment]
@ErfanOrangetoolz @jdegger I am also facing same problem,  incoming call not working but its ringing

**Comment by sahil8453** [comment]
+1
