### ISSUE TITLE
Question: Do i need to create different push credential on Twilio console for IOS and Android?

### ISSUE THREAD

**Issue by salman-pixarsart** [hoxfon/react-native-twilio-programmable-voice#178]
I'm trying to setup Twilio with FCM. Do I need to create different Push Credentials for IOS and Android? Or It will work using the one FCM Push Credentials. Any example would be helpful.

**Comment by mustafa5199** [comment]
@salman-pixarsart , yeah you need to create differebt Push Credentials for IOS and Android. Because push notifications for IOS it handled through APNS and for Android it get handled through FCM.

**Comment by salman-pixarsart** [comment]
That means for IOS, FCM tokens won't be required. APN token would be sent through the Voice.Register method?

**Comment by salman-pixarsart** [comment]
And do I need to manage to 2 push credentials SIDs on the server-side?

**Comment by salman-pixarsart** [comment]
Closing this issue since it's not the right place to ask backend questions.
