### ISSUE TITLE
call doesn't disconnect when the App stops

### ISSUE THREAD

**Issue by fabriziomoscon** [hoxfon/react-native-twilio-programmable-voice#18]
RN 0.41.2
lib 0.6.0
Android ONE PLUS 3

When the App is closed from the tray, or dismissed the `onHostDestroy()` method is not called and the active call is not terminated

**Comment by jdegger** [comment]
I don't think this issue is still valid @fabriziomoscon, closing as I have never seen this behavior in current implementation. We can reopen if needed.
