### ISSUE TITLE
Ios Unregister device problem

### ISSUE THREAD

**Issue by atishbarua** [hoxfon/react-native-twilio-programmable-voice#180]
I am using react-native-twilio-programmable-voice for IOS. There is a function to unregister device from twilio. After unregister, how to reregister device again? Because after unregister, no incoming calls comes through. even if i initialize twiliovoice again. and configure callkit again.

**Comment by atishbarua** [comment]
Problem solved

**Comment by tragicmj** [comment]
@atishbarua how??
