### ISSUE TITLE
Call notification is not being shown consistently when the app is in closed state ( IOS ).

### ISSUE THREAD

**Issue by salman-pixarsart** [hoxfon/react-native-twilio-programmable-voice#183]
Hi there!  I'm receiving calls when the app is in the foreground and background but not when the app is closed.
When I call when the app is in quit state nothing happens except the metro bundler refresh itself. Thats the only indication that something is being received but I'm not able to debug it.

![Screenshot 2021-01-05 at 5 54 34 PM](https://user-images.githubusercontent.com/69501240/103648760-2b403080-4f7f-11eb-9cb5-b6817126d162.png)

Any help or cue will be appreciated.

Did you follow all the instructions as specified in the Twilio Quickstart repositories?
Yes followed all the steps.

What version of React Native are you running?
0.63.3

What version of react-native-twilio-programmable-voice are you running?
4.3.0

What device are you using? (e.g iOS10 simulator, Android 7 device)?
IOS 14.2 -  Iphone 7 plus

Is your app running in foreground, background or not running?
Not Running.

Is there any relevant message in the log?

If using iOS, which pod version are you using?
5.5.1

Advanced:
Have you tried adding breakpoint using AndroidStudio or XCode and analyze the logs?
There no log when the app is in a quit state.

can share a project with the issue?
It's a closed source project.

Did you try to reinstall the pods completely?
Yes, I tried to reinstall the pods completely.

**Comment by salman-pixarsart** [comment]
@jdegger Can you help me with this one? I'm receiving calls in the background and foreground but not when the app is in the closed state.

**Comment by salman-pixarsart** [comment]
Incoming notification is working now. But for the first time when we call on the app, There's no incoming call invitation. After a couple of calls, Incoming calls start to receive on the IOS app.

**Comment by salman-pixarsart** [comment]
The incoming call is not consistent. When the app is open we only receive call consistently. Otherwise It sometime invoke call screen ( CallKit ) and sometime it don't. @jdegger  How can I debug this?

**Comment by salman-pixarsart** [comment]
The incoming call is not consistent. When the app is open we only receive call consistently. Otherwise It sometime invoke call screen ( CallKit ) and sometime it don't. @jdegger  How can I debug this?

**Comment by salman-pixarsart** [comment]
I've opened an issue regarding this in "twilio/voice-quickstart-ios" repository as well and they have said this.
![Screenshot 2021-01-08 at 11 37 07 AM](https://user-images.githubusercontent.com/69501240/103982890-27422780-51a6-11eb-8559-2aad70ff1706.png)

@jdegger How can I achieve this in react-native to solve this issue since I'm not an IOS developer?

**Comment by Samsritha1596** [comment]
@salman-pixarsart It will work in release build for app closed state

**Comment by salman-pixarsart** [comment]
I'll give it a try. Thanks @Samsritha1596  for your response.

**Comment by marvin-abella-coloma** [comment]
Hi @Samsritha1596 I've tried that way but still not working. 
![image](https://user-images.githubusercontent.com/46912772/128555646-5865f895-1848-4e6c-8367-00d75820cd0d.png)
When receiving the call on the app killed state, I can see the javascript initialization. Also, the deviceDidReceiveIncoming handler is triggered. But the Incoming CallKit UI didn't open. 

On the second call( once the app is already opened or initialized state) the app is working well. 

Can you please give me the advice? Thank you. 

Did you follow all the instructions as specified in the Twilio Quickstart repositories?
Yes followed all the steps.

What version of React Native are you running?
0.63.3

What version of react-native-twilio-programmable-voice are you running?
4.4.1

What device are you using? (e.g iOS10 simulator, Android 7 device)?
IOS 14.2 - Iphone 6

Is your app running in foreground, background or not running?
Not Running.

Is there any relevant message in the log?
Attached. 

If using iOS, which pod version are you using?
5.5.1
