### ISSUE TITLE
How to show App Icon in Callkit? What is "image_name_in_bundle" in configure callkit?

### ISSUE THREAD

**Issue by salman-pixarsart** [hoxfon/react-native-twilio-programmable-voice#187]
I'm trying to add App Icon in Callkit. I get it there's a param in configureCallKit() method but its just getting the imageName ( name of the image included in the bundle). How do I reference image my AppIcon.

![Screenshot 2021-01-21 at 1 51 39 PM](https://user-images.githubusercontent.com/69501240/105327091-51f19e80-5bf0-11eb-88e3-1b8c5322d196.png)

What is "image_name_in_bundle"?

Did you follow all the instructions as specified in the Twilio Quickstart repositories?
Yes
What version of React Native are you running?
0.63.3
What version of react-native-twilio-programmable-voice are you running?
4.3.0
What device are you using? (e.g iOS10 simulator, Android 7 device)?
Iphone 7 Plus
Is your app running in foreground, background or not running?
Not Applicableble
Is there any relevant message in the log?
No
If using iOS, which pod version are you using?
5.1.1

Step to reproduce

Advanced:
Have you tried adding break point using AndroidStudio or XCode and analyse the logs?
can share a project with issue?
Did you try to reinstall the pods completely?

**Comment by jdegger** [comment]
Hi this is the file name of whatever is in your asset folder. If your bundle is configured correctly, all the images in your project will be included and can be used in this case.

Note that you just place the file somewhere in your react JavaScript project, you don't have to do this in xcode.

**Comment by salman-pixarsart** [comment]
Hi @jdegger. Suppose I've a image **AppIcon.png** in my assets folder in my Project. Would I be applying the like I've done below?
```
            TwilioVoice.configureCallKit({
              appName: 'MyAppName',
              imageName: 'AppIcon',
            });
```
I've tried this with Bundled Image but It is not showing up on the callkit.

**Comment by jdegger** [comment]
It should be `imageName: 'AppIcon.png'`, does that work?

**Comment by usamaabutt** [comment]
@jdegger i have tried this but it's not working
