### ISSUE TITLE
Push notifications for missed calls and voicemail

### ISSUE THREAD

**Issue by danstepanov** [hoxfon/react-native-twilio-programmable-voice#198]
Please include the following information for better support

The more context you provide around this issue the faster the community can help you

Did you follow all the instructions as specified in the Twilio Quickstart repositories? Yes
What version of React Native are you running? 0.63.4
What version of react-native-twilio-programmable-voice are you running? 4.4.0
What device are you using? (e.g iOS10 simulator, Android 7 device)? iPhone Xs
Is your app running in foreground, background or not running? not running
Is there any relevant message in the log? no
If using iOS, which pod version are you using? ~> 5.2.0

Step to reproduce N/A

Just wondering if there is a way to show a push notification for when a call is missed or if there is a new voicemail. Not sure if that is within the scope of this library but having trouble finding anything via google.

**Comment by jdegger** [comment]
Hi @danstepanov, thank you for your ticket.

This is indeed a bit out of scope, however I will try to answer your question. Missed calls can be detected through the currently existing events: incoming call + no answer means that it's missed, you can handle this in your own application.

Calls are also the native phone dialer on iOS and Android in the history.

In summary: you'd have to add this logic yourself in the app
