### ISSUE TITLE
Achieving UX parity with Android default "phone" app

### ISSUE THREAD

**Issue by jrperson** [hoxfon/react-native-twilio-programmable-voice#20]
React Native: 42
react-native-twilio-programmable-voice: 0.6.2
Device: Nexus 6 (Android 7)

What I am experiencing currently is any inbound call opens the app (if not already in foreground) and creates a notification in all app states (background, foreground, screen off).  The notification does not show on screen, just in the status bar.

The default Android phone app does things differently for inbound calls.
1. When device screen is off the phone app functions just like this library.  It opens the app in foreground to an "answer/reject" style page of the phone app itself.  It also puts a notification in the status bar (not onscreen).

2. But, when app is in foreground and background a notification is shown on screen, but the app does not come to foreground automatically.  If rejected, the app does not open and notification goes away.  If answered, the app comes to foreground and notification is modified.

I am not yet familiar enough with the Android API to modify the NotificationHelper.java code itself to achieve UX on parity with the default phone app.  Would this be controlled in the "getLaunchIntent"...or maybe the "NotificationCompat.Builder"s themselves?  I am not yet seeing where to modify this behavior.  Any pointers would be appreciated.

**Comment by fabriziomoscon** [comment]
@jrperson in my app the incoming call notification opens the react native app. What is your `AndroidManifest.xml`?

The relevant code is this block:
https://github.com/hoxfon/react-native-twilio-programmable-voice/blob/master/android/src/main/java/com/hoxfon/react/TwilioVoice/NotificationHelper.java#L78-L107
Basically create an App launch intent to use when the notification is dealt with.

I think this is relevant:
```
<activity
            android:name=".MainActivity"
            android:label="@string/APP_NAME"
            android:launchMode="singleTop" //<--------
            android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
            android:windowSoftInputMode="adjustResize"
            android:screenOrientation="portrait">
```

**Comment by jrperson** [comment]
@fabriziomoscon Yes, that is the exact experience I am having "incoming call notification opens the react native app."  That is not what I want to have happen.  I only want the incoming call notification to trigger an opening of the react native app when the screen is off.  All other times (screen on/ app in background, screen on/app in foreground) I just want the notification to show onscreen (but the react native app does not open).  This is more in line with the default "phone" app behavior for Android.

Because what I am looking for is conditional behavior
```
if(screen off) {
  open app;
}
else {
  don't open app;
  just show notification on screen;
}
```
I assumed it wouldn't be a simple AndroidManifest.xml value.

**Comment by fabriziomoscon** [comment]
Yes, sorry for the confusion. What you described it is what happens.
It might be good to have a session on hangout or seeing a GIF on what happens.

It might also be worth reading this thread:
https://github.com/hoxfon/react-native-twilio-programmable-voice/issues/12

Let's organise a time so I can help you.

**Comment by fabriziomoscon** [comment]
@jrperson is this still an issue? Check out the latest branch which uses the latest Twilio SDK for iOS and Android.
