### ISSUE TITLE
React Native android build failed while running app after install -  npm install react-native-twilio-programmable-voice --save

### ISSUE THREAD

**Issue by neonithya** [hoxfon/react-native-twilio-programmable-voice#214]
React Native android build failed while running app after install -  npm install react-native-twilio-programmable-voice --save
The more context you provide around this issue the faster the community can help you

version of React Native are you running -0.68.2
version of react-native-twilio-programmable-voice are you running - ^4.4.0
device  using -  Android 11 device

Message in the log

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.getkeepsafe.relinker:relinker:1.2.2.
     Searched in the following locations:
       - file:/Users/neosoft/Documents/Project/test_voice/node_modules/react-native/android/com/getkeepsafe/relinker/relinker/1.2.2/relinker-1.2.2.pom
       - file:/Users/neosoft/Documents/Project/test_voice/node_modules/jsc-android/dist/com/getkeepsafe/relinker/relinker/1.2.2/relinker-1.2.2.pom
       - https://repo.maven.apache.org/maven2/com/getkeepsafe/relinker/relinker/1.2.2/relinker-1.2.2.pom
       - https://dl.google.com/dl/android/maven2/com/getkeepsafe/relinker/relinker/1.2.2/relinker-1.2.2.pom
       - https://www.jitpack.io/com/getkeepsafe/relinker/relinker/1.2.2/relinker-1.2.2.pom
     Required by:
         project :app > project :react-native-twilio-programmable-voice > com.twilio:voice-android:4.5.0

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.getkeepsafe.relinker:relinker:1.2.2.
     Searched in the following locations:
       - file:/Users/neosoft/Documents/Project/test_voice/node_modules/react-native/android/com/getkeepsafe/relinker/relinker/1.2.2/relinker-1.2.2.pom
       - file:/Users/neosoft/Documents/Project/test_voice/node_modules/jsc-android/dist/com/getkeepsafe/relinker/relinker/1.2.2/relinker-1.2.2.pom
       - https://repo.maven.apache.org/maven2/com/getkeepsafe/relinker/relinker/1.2.2/relinker-1.2.2.pom
       - https://dl.google.com/dl/android/maven2/com/getkeepsafe/relinker/relinker/1.2.2/relinker-1.2.2.pom
       - https://www.jitpack.io/com/getkeepsafe/relinker/relinker/1.2.2/relinker-1.2.2.pom
     Required by:
         project :app > project :react-native-twilio-programmable-voice > com.twilio:voice-android:4.5.0

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s

Here is
android/build.gradle

import org.apache.tools.ant.taskdefs.condition.Os

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31

        if (System.properties['os.arch'] == "aarch64") {
            // For M1 Users we need to use the NDK 24 which added support for aarch64
            ndkVersion = "24.0.8215888"
        } else {
            // Otherwise we default to the side-by-side NDK version from AGP.
            ndkVersion = "21.4.7075529"
        }
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:7.0.4")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("de.undercouch:gradle-download-task:4.1.2")
        classpath 'com.google.gms:google-services:4.3.10'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        mavenCentral {
            // We don't want to fetch react-native from Maven Central as there are
            // older versions over there.
            content {
                excludeGroup "com.facebook.react"
            }
        }
        google()
        maven { url 'https://www.jitpack.io' }
    }
}
apply plugin: 'com.google.gms.google-services'

**Comment by huzaifa3115** [comment]
Can you please add solution?

**Comment by usmanrwp** [comment]
Add `implementation 'com.getkeepsafe.relinker:relinker:1.4.4'` in app level gradle . Android -> App -> build.gradle
