### ISSUE TITLE
How can I call App to App?

### ISSUE THREAD

**Issue by mcmatan** [hoxfon/react-native-twilio-programmable-voice#24]
I am trying to update from this repo: https://github.com/rogchap/react-native-twilio

But my app users App to app calling, no numbers.
Is this possible with this repo?

**Comment by nkarman** [comment]
Hey @mcmatan, I have this running in my app. You need to utilize Twilio Client, which allows you to call between apps by passing 'usernames'. 

To answer your question, yes this is possible. TwilioVoice.connect(to: 'username') allows you to connect to another user if they have a twilio device initialized with a Twilio access token that contains their username as the identity portion in the payload of the token. Hope this helps!

**Comment by RUIFERNANDE5** [comment]
@nkarman In a real use case you would be calling a userId and not a username. Do you have any clue how to give a friendly name in a voice call?
