### ISSUE TITLE
IOS Cannot receive calls when app is closed

### ISSUE THREAD

**Issue by mcmatan** [hoxfon/react-native-twilio-programmable-voice#25]
Maybe this is becouse ReactNative is too heavy to load in background

**Comment by fabriziomoscon** [comment]
eheh :)
no that is not the case.
Sorry I didn't see this post earlier.
I do receive calls. I have other issues at the moment, but receiving now is sorted.
Check this thread:
https://github.com/twilio/voice-quickstart-objc/issues/33

I was using sandbox=false for release build from xcode, but that would work only for Apple releases, like TestFlight of iTunes.

Let me know when you manage to sort it out. The guys at Twilio are awesome to help with this problems. If nothing of what you read on that other repo helps you I would suggest to open a new issue there.

By the way, if anyone is interesting in helping out on ios, please do!
