### ISSUE TITLE
iOS Crashing upon connect() - nil call_sid

### ISSUE THREAD

**Issue by nkarman** [hoxfon/react-native-twilio-programmable-voice#26]
React-Native 0.37
React-Native-Twilio-Programmable-Voice 2.2.0
iOS10 simulator
App in foreground
Pod version = 2.0.0

Upon attempting to place an outgoing call, the app crashes with NSInvalidArgumentException with reason 'setObjectForKey: object cannot be nil (key: call_sid)'

I am also getting X-Twilio-Error: 31201 which is a 'generic unknown error'.

This is after receiving a valid twilio auth token from our server, and then initializing twilio with that valid token.

The outgoing call is to a valid phone number.

I can provide additional console output if helpful!

**Comment by Pagebakers** [comment]
Getting the same errors with RN 46.1 running on iPhone

**Comment by Pagebakers** [comment]
The crash was due to a connection error (unauthorized in my case)

Commenting this line fixes it.
https://github.com/hoxfon/react-native-twilio-programmable-voice/blob/master/ios/RNTwilioVoice/RNTwilioVoice.m#L304

**Comment by nkarman** [comment]
The root of my problem was that I was putting whitespace in my access token identity server side.

**Comment by Pagebakers** [comment]
I don't think this should be closed, since the error handler is handling thing improperly making the app crash.

**Comment by fabriziomoscon** [comment]
@nkarman could this issue be related to you trying to use a newer version of the Twilio SDK in your podfile?
As of version `2.5.0` I have integrated the callSid changes make in the SDK so you can use beta13 in your podfile.
Please let me know if that fixed the issue for you.

callSid changes:
https://www.twilio.com/docs/api/voice-sdk/ios/changelog#200-beta12-july-11-2017

**Comment by Pagebakers** [comment]
Looks like this resolved the issue, thanks!

**Comment by rochapablo** [comment]
I'm getting ```Error handling FCM messagecom.twilio.voice.MessageException: No CallInvite with this CallSid``` even though the call had worked.

Could I be missing something?

**Comment by fabriziomoscon** [comment]
Hi @rochapablo, are you sure you're issue is related to this one?
To me it sounds quite different. Anyway I really think we need more context around this issue.
Please open a new one and try to provide us with more information and step to reproduce.
Sorry for the inconvenience

**Comment by lassandroan** [comment]
We're on the team from @nkarman's original post and this is still happening for us

React-Native 0.49.0
React-Native-Twilio-Programmable-Voice 3.2.0
Twilio Voice 2.0.0-beta13 & 2.0.0-beta15
iPhone 6 running iOS 11.1.1
App in foreground
Pod version 1.3.0

The issues happens in the `connectionDidConnect` delegate method, so I have a feeling this may be something more related to the Twilio SDK or possibly connection errors as mentioned before.

We've been able to reproduce it where the first call succeeds and then every call after that fails with the same null sid error.

Do you have any insights?

**Comment by fabriziomoscon** [comment]
I would compile the example app from Twilio:
https://github.com/twilio/voice-quickstart-objc/tree/master/ObjCVoiceCallKitQuickstart
and run it with no significant changes to your backend.
If the crash persists, the problem lies with either your configuration of the server of Twilio SDK.

The crash originally reported means that `call` is `nil`
```
#pragma mark - TVOCallDelegate
- (void)callDidConnect:(TVOCall *)call {
  [...]
  NSMutableDictionary *callParams = [[NSMutableDictionary alloc] init];
  [callParams setObject:call.sid forKey:@"call_sid"];
  [...]
  [self sendEventWithName:@"connectionDidConnect" body:callParams];
}
```

I can't see how the `TVOCallDelegate` would pass a `nil` call.
