### ISSUE TITLE
iOS - handler is not a function. (In 'handler(rtn)', 'handler' is undefined)

### ISSUE THREAD

**Issue by nkarman** [hoxfon/react-native-twilio-programmable-voice#27]
I get this issue running on both iOS Simulator and on iPhone 6. This occurs immediately once the call starts ringing. This error is dismissible, and does not cause the app to crash. I am adding all of the necessary event listeners to the TwilioVoice Instance. 

This error is originating from line 88 in index.js

Thanks in advance!

**Comment by nkarman** [comment]
@hoxfon @jrperson Have either of you experienced this issue? Thanks!

**Comment by fabriziomoscon** [comment]
@nkarman is there any chance that you are passing to the listener an undefined reference?

In my JS app I have something like this:
```js
 //...
       TwilioVoice.addEventListener('deviceReady', _deviceReady)
        if (Platform.OS !== 'ios') {
            TwilioVoice.addEventListener('deviceNotReady', _deviceNotReady)
        }
 //...
        if (Platform.OS !== 'ios') {
            TwilioVoice.addEventListener('deviceDidReceiveIncoming', _deviceDidReceiveIncoming)
        }
        if (Platform.OS === 'ios') {
            TwilioVoice.addEventListener('callRejected', _deviceCallRejected)
        }
        TwilioVoice.addEventListener('connectionDidConnect', _connectionDidConnect)
        TwilioVoice.addEventListener('connectionDidDisconnect', _connectionDidDisconnect)
```

let me know if that helps

**Comment by nkarman** [comment]
@fabriziomoscon I have something very similar. Do you think you could possibly provide an example of where the listeners are defined? such as _deviceReady or _connectionDidConnect? In my code, I have them defined as such 

```
  _connectionDidConnect (args) {
    console.tron.log('connectionDidConnect', args)
  }

  _connectionDidDisconnectHandler (error) {
    console.log('connectionDidDisconnectHandler', error)
  }
```

**Comment by benminer** [comment]
I am also getting this issue.

**Comment by fabriziomoscon** [comment]
Please paste your file, there is really nothing special in my _ handlers

**Comment by benminer** [comment]
Hey @fabriziomoscon, thanks for replying. I actually figured it out shortly after posting, should of deleted it. Thank you very much for writing this module!

**Comment by fabriziomoscon** [comment]
My pleasure, maybe you could post your solution anyway for others.
