### ISSUE TITLE
Android On incoming call when task is dismissed the notification tap have no effect

### ISSUE THREAD

**Issue by fabriziomoscon** [hoxfon/react-native-twilio-programmable-voice#28]
`react-native 0.50.4`
`react-native-twilio-programmable-voice 3.18.0`
Android One Plus 3
Android v 8.0.0

when there is an incoming call regardless of the app being on the foreground, when the app gets killed the incoming call notification stays, but neither of the button works.

Ideally the ANSWER button would restart the app, the REJECT button would reject the call and dismiss the incoming call notification.

If anyone knows how to handle this situation correctly, any help would be greatly appreciated.

**Comment by fabriziomoscon** [comment]
related to #18

**Comment by jdegger** [comment]
Closing this issue as this is handled by a CallKeep-like solution perfectly.
