### ISSUE TITLE
`TwilioVoice.initWithToken()` and `TwilioVoice.connect()` did not work properly on iOS 10.2 simulator

### ISSUE THREAD

**Issue by oshimayoan** [hoxfon/react-native-twilio-programmable-voice#33]
`TwilioVoice.initWithToken()` and `TwilioVoice.connect()` did not work properly, after `connect` executed it nothing is happening. 
And also whatever the token used on `initWithToken` (e.g. random string), it always return:
```
{
  initilized: true,
}
```

Here is the code that I use:
```
import React, {Component} from 'react';
import {StyleSheet, Text, View, Button} from 'react-native';
import TwilioVoice from 'react-native-twilio-programmable-voice';

export default class App extends Component {
  constructor() {
    super(...arguments);
    this.state = {
      success: false,
    };
  }

  async componentWillMount() {
    try {
      let success = await TwilioVoice.initWithToken('token');
      console.log(success);
      this.setState({success});
      TwilioVoice.addEventListener('connectionDidConnect', () => {
        console.log('>> TwilioVoice, Call connected.');
      });
      TwilioVoice.addEventListener('connectionDidDisconnect', () => {
        console.log('>> TwilioVoice, Call disconnected.');
      });
    } catch (e) {
      console.log('error token:', e);
    }
  }

render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>Welcome!</Text>
        <Button
          title="Call"
          onPress={() => {
            if (this.state.success && this.state.success.initilized) {
              try {
                console.log('>> TwilioVoice, Calling...');
                TwilioVoice.connect({To: '+62123456789'});
              } catch (e) {
                console.log('>> error:', e);
              }
            }
          }}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
});
```

What version of React Native are you running?
> I use RN v0.47.2

What version of react-native-twilio-programmable-voice are you running?
> I use v2.8.0

What device are you using? (e.g iOS9 simulator, Android 6 device)?
> I use iOS 10.2 simulator

Is your app running in foreground, background or not running?
> It's running on foreground

Is there any relevant message in the log?
> Nope, nothing

If using iOS, which pod version are you using?
> I use pod v1.31

Step to reproduce
> Just run it normally

**Comment by rochapablo** [comment]
@oshimayoan is there any error in the log?

**Comment by oshimayoan** [comment]
@rochapablo There is no single error in the log. And this `console.log` is always get called:
```
console.log('>> TwilioVoice, Calling...');
```

**Comment by rochapablo** [comment]
@oshimayoan did you get somewhere?

**Comment by skeet** [comment]
@fabriziomoscon Do you have a version where this is working? Would love to see some code and know what versions you're using if so. I'd be happy to write up a detailed guide if I can get a simple call working. I don't know if my issues are to do with the version of RN I'm using or the version of `react-native-twilio-programmable-voice` (using the latest for both), or if it's to do with the credentials the access token is using.

Thanks.

**Comment by fabriziomoscon** [comment]
Hi,
I am using version 2.8 with RN 0.45 and I don't experience any problems connecting.
As a first troubleshooting I will always recommend to try and run a compete working example with the official twilio quickstart apps. Once that works you would exclude any possibilities of misconfiguration with access tokens.

Once Callkit is initialised you can clearly read about it inside xcode logs. If you can't see that, there are issues on initialization.
The fact that init always returns initialized: true is not ideal. I made it so to even up the behaviour between android and iOS, since that allows for JavaScript simplifications in the code that uses the library.

Please let me know if this helps at all

**Comment by skeet** [comment]
@fabriziomoscon Thanks mate, will give it another try and report back.

**Comment by oshimayoan** [comment]
Sorry for late to report that we did something wrong from the start, we didn't deploy any server because we thought that twilio will automatically handle that part. But we were wrong, so after we deploy a server to handle the communication with twilio, it did worked smoothly.

But now the problem is the incoming call, do you guys have any idea why the app on iOS device didn't receive any call from phone (PSTN) call? Even though the status on the phone who do the call is `connected` and the timer showed up, but then the call is automatically disconnected after 10-15 seconds.

So is there any issue with the `callKit` itself or is there some setup that we missed?

**Comment by fabriziomoscon** [comment]
I am very happy to hear that you managed to make calls!
Make sure you follow this first:
https://github.com/twilio/voice-quickstart-objc#7-create-voip-service-certificate

When you want to receive calls on the simulator or device for a debug build you must create a debug certificate on Twilio.
Only the ios version for TestFlight and app store must have a twilio certificate with debug false.
I also had issue to make receiving calls working and I received tons of help directly from support at twilio.

I think it is safe to close this issue, please reopen if you encounter the same problem.

**Comment by oshimayoan** [comment]
Thanks!

I did create the voip service certificate and configure it on `push credentials` in twilio. But the app still do not get any push notification from the call. Does it has anything todo with this?
https://www.twilio.com/docs/api/notify/guides/register-for-notifications-ios

I also seen that on your code you already set [this](https://developer.apple.com/library/content/documentation/Performance/Conceptual/EnergyGuide-iOS/OptimizeVoIP.html) up, should I set it up again on my app or not?

Could you explain it more detail to me what do you mean with `debug false`?

**Comment by fabriziomoscon** [comment]
Careful! You are reading the Twilio notify docs :) that has nothing to do with Voice.

Sorry for the confusion about `debug false` the terminology used by Twilio is sandbox.
https://github.com/twilio/voice-quickstart-objc#8-create-a-push-credential-with-your-voip-service-certificate
For simulator and all ad hoc built not processed by Apple set `sandbox = true`

If you search online there are tools to simulate push notification, so you could test it faster and see it the app sees the notifications coming in the Xcode log.

Did you manage to run and receive calls using the official Twilio Quickstart app? If not I strongly recommend you to do so first.

**Comment by oshimayoan** [comment]
Thanks a lot for your help! Now we able to do the incoming call! We are so excited about it! :)

It seems that we have the wrong flow of getting the token and misunderstood about what the `identity` is for.

Currently we are a bit confused about when a PSTN do a call to the app, how it will know which client to dial? Do we have to do something like `extension` thing? Or is there any best practices for that?

Sorry if we are asking too much.

**Comment by fabriziomoscon** [comment]
I am glad to hear that!
Twilio when receiving a PSTN call will make an http request to your server on the URL you specified for the twml app. At that stage you will respond with a twml command to dial a client name, which client name to dial is up to you, maybe you will look up into a database, basically you become the switching board

**Comment by oshimayoan** [comment]
So if I have two clients name with same number, the caller (PSTN) can't decide which client to dial?
So we have to make a default which one to dial, right?

**Comment by fabriziomoscon** [comment]
you must pick client name unique. For example `client:+123456789` or `client:unique@gmail.com`.
each client in you app will have some twilio phone numbers registered to them.
When you receive an incoming call, twilio "tells" you which number was called, so you can use it to look up in your database to know which client to <Dial>

**Comment by oshimayoan** [comment]
Ah so one twilio phone number is only for one client?

**Comment by fabriziomoscon** [comment]
no, a client can have many numbers.
I encourage you to re-read the documentation for the Twilio API and ask any questions directly to support@twilio.com they are great at helping new comers and they always helped me when I had doubts similar to yours.
I can provide you help with issues for the library, but to understand how to use Twilio for your specific app and use case, they will surely be more qualified and precise in pointing you to the correct direction.
