### ISSUE TITLE
Audio Error

### ISSUE THREAD

**Issue by rochapablo** [hoxfon/react-native-twilio-programmable-voice#34]
Please include following information for better support

What version of React Native are you running?
*0.47.2*

What version of react-native-twilio-programmable-voice are you running?
*2.8.0*

What device are you using? (e.g iOS9 simulator, Android 6 device)?
*iOS10.3*

Is your app running in foreground, background or not running?
*foreground*

Is there any relevant message in the log?

```
<Warning>: 'token:', { identity: 'IgnominiousCameronNevis', token: '...' }
<Warning>: CallKit Initialized
<Warning>: providerDidBegin
<Notice>: '_deviceReady', undefined
<Warning>: Calling phone number ...
```

```
<Error>: [avas] AVAudioSessionUtilities.h:112:GetProperty: AudioSessionGetProperty ('acat') failed with error: '!ini'
<Error>: [avas] AVAudioSessionUtilities.h:125:GetProperty_DefaultToZero: AudioSessionGetProperty ('acat') failed with error: '!ini'
<Error>: [avas] AVAudioSession.mm:852:-[AVAudioSession category]: No valid string for category: 0
<Error>: [avas] AVAudioSessionUtilities.h:112:GetProperty: AudioSessionGetProperty ('mode') failed with error: '!ini'
<Error>: [avas] AVAudioSessionUtilities.h:125:GetProperty_DefaultToZero: AudioSessionGetProperty ('mode') failed with error: '!ini'
<Error>: [avas] AVAudioSession.mm:1575:-[AVAudioSession mode]: No valid string for mode: 0
```

```
<Warning>: StartCallAction transaction request successful
<Warning>: provider:performStartCallAction
<Warning>: Ignoring assertion request named "com.apple.AddressBook.Search" from <BSProcessHandle: 0x7fbaccd0b920; callservicesd:3848; valid: YES> because process { pid 3848; bundleID (null) } is unknown.
    com.apple.CallKit.CallDirectory[4233]
```

```
<Error>: [Default] Unable to initialize CXCallDirectoryStore for reading: Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “CallDirectory” in the folder “Library”." UserInfo={NSFilePath=/var/mobile/Library/CallDirectory, NSUnderlyingError=0x7fe83a50c620 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}}
<Error>: [Default] Error retrieving call directory first identification entry for phone number ...: Error Domain=com.apple.CallKit.error.calldirectorymanager Code=0 "(null)"
```

```
<Warning>: provider:didActivateAudioSession
```

If using iOS, which pod version are you using?

Step to reproduce

I'm just setting the token and making a call.

```
fetch('https://.../token')
.then((response) => response.json())
.then((response) => {
Twilio.initWithToken(response.token)
Twilio.initWithTokenUrl('https://.../token')
```

```
Twilio.connect({
      To: number
    })
```

Advanced:
Have you tried adding break point in native handlers and see the logs printed?
can share a project with issue?
Did you try to reinstall the pods completely?

The more context you provide around this issue the faster the community can help you.

**Comment by skeet** [comment]
I get exactly the same issue. Can anyone confirm that this library actually works?

Am I right in assuming it won't run on the simulator?

**Comment by rochapablo** [comment]
I'm still working on, but yes It will work only running into your phone.

**Comment by fabriziomoscon** [comment]
Hi guys,
Thanks for using the library.
I can confirm that the library correctly setup with debug certificates and Callkit profiles will work for both making and receiving calls in the simulator.

In the log I can see bundleId = null and a couple of permission denied errors. By the look of it sounds you guys are having issues registering with all required Apple certificates and profiles. It's a painful but sadly necessary step.

Please let me know if you could funnel further the issues.

**Comment by fabriziomoscon** [comment]
@rochapablo 
I believed you have fixed your issues. There is also a new library version that you can try out. v3.12.0 is now on npm.
In the steps to reproduce your issue you have a double token initiation:

```JavaScript
Twilio.initWithToken(response.token)
Twilio.initWithTokenUrl('https://.../token')
```
Please use only one of those 2 lines because they are equivalent.
