### ISSUE TITLE
Android Null object reference ActivityCompat

### ISSUE THREAD

**Issue by RUIFERNANDE5** [hoxfon/react-native-twilio-programmable-voice#45]
RN: 0.47.2
react-native-twilio-programmable-voice: "^3.2.0"

On android, following the installation guide I'm getting the following error on run-android debug (device huawei honor 8 6.0).

![22414737_507282749628632_801875250_n](https://user-images.githubusercontent.com/7592536/31494496-6b4d3aec-af4b-11e7-83a6-991deaeb850b.png)

Any clue? Thanks in advance.

**EDIT:**

**Comment by sumesh1993** [comment]
@RUIFERNANDE5 Were you able to fix this issue ? Facing the same error. Any help will be appreciated.
