### ISSUE TITLE
Documentation - initWithTokenUrl and configureCallKit

### ISSUE THREAD

**Issue by RUIFERNANDE5** [hoxfon/react-native-twilio-programmable-voice#46]
**RN:** "0.47"
**package v:** "3.2.0"

I can't really understand the documentation, in my use case I only need to make calls via userName > userName. 
Am I obligated to configure `CallKit`? If so, whats the `appName` param?
Also, the `initWithTokenUrl` function, expects the get Token url, am I correct? What object should the server return?

I already tried to return a `{token: '...'}` a `{'....'}`and an {`accessToken: '...'`}. But I get the following error everytime:
`An error occurred while registering: Invalid access token header`;

Also, I can successfully login using  `initWithToken` but can't seem to connect to anyone. It says "calling number {`identity`}" on xcode console but none of the events get trigger nor in my client nor in the other device.

Thanks in advance.

**Comment by RUIFERNANDE5** [comment]
I've succesfully implemented `ConfigureCallKit`, giving the same app name present in Xcode. 
Didn't use `initWithTokenUrl`, for what I understood in ObjC code, initWithTokenUrl and initWithToken lead to the same result.
Probably something to add on docs tho. 
Thanks.

**Comment by topjun** [comment]
Hi, can you please share how you had resolved `Invalid access token header` issue? I have the same issue and don't know how to make it work. I simply retrieve token from my local `https://4f155c65.ngrok.io/token` server and verified the token. however I still received `invalid access token header'. thanks!!!
