### ISSUE TITLE
shouldShowRequestPermissionRational nul object reference

### ISSUE THREAD

**Issue by RUIFERNANDE5** [hoxfon/react-native-twilio-programmable-voice#47]
Please include following information for better support

**What version of React Native are you running?** "0.49.3"
**What version of react-native-twilio-programmable-voice are you running?** "^3.2.0"
**What device are you using?** Android 6 Device
**Is your app running in foreground, background or not running?** Runtime
**Is there any relevant message in the log?** `Attempt to invoke virtual method 'boolean android.app.Activity.shouldShowRequestPermissionRationale(java.lang.String)' on a null object reference.`

If i remove the `requestPermissionForMicrophone` function isnide TwilioVoiceModule.java the error disappears.
I'm also requesting permission as recommended in app and manifest.
Any clue whats triggering the error?

**Comment by fabriziomoscon** [comment]
Hi there,
thank you for reporting this issue.
It was also reported here: https://github.com/hoxfon/react-native-twilio-programmable-voice/pull/43 so I really think there are issues with the microphone permissions.
For the time being I would recommend removing the function `requestPermissionForMicrophone` as you have already done and wait for a fix.

I am sorry I don't have a better answer right now.

**Comment by RUIFERNANDE5** [comment]
I'll keep this open since #43 doesn't specify it has a bug but a user preference.

**Comment by jakeopena** [comment]
I got the same error. Any update?

Following the instruction, the error disappears when removing function call to `requestPermissionForMicrophone`.

Now when the **RECORD_AUDIO** permission is not granted yet and I start the call, there is an error **Requires the RECORD_AUDIO permission**.

Thanks.

**Comment by kevng9** [comment]
@jakeopena 

I got around that by checking for permissions while initializing the calling class. So in my call screen I have the following code in the constructor:

```
    util = new Utils();
    if (Platform.OS === 'android'){util.checkMicrophonePermission();}
```

And within the Util class I have the following two functions
```
import { PermissionsAndroid } from 'react-native';

async requestMicrophonePermission() {
    try {
      const granted = await PermissionsAndroid.request(
        PermissionsAndroid.PERMISSIONS.RECORD_AUDIO,
        {
          'title': 'Microphone Permission',
          'message': 'App needs access to you microphone ' +
                     'so you can talk with other users.'
        }
      )
      if (granted === PermissionsAndroid.RESULTS.GRANTED) {
        console.log("You can use the microphone")
      } else {
        console.log("Microphone permission denied")
      }
    } catch (err) {
      console.warn(err)
    }
  }

  checkMicrophonePermission(){
    PermissionsAndroid.check(PermissionsAndroid.PERMISSIONS.RECORD_AUDIO).then((result)=>{
      if(!result){
        this.requestMicrophonePermission();
      }
    });
  }
```

**Comment by fabriziomoscon** [comment]
Guys I will not be able to follow up directly this issue with code in the short term, so please feel free to workout a solution for this issue and submit a PR.
Thanks

**Comment by codingwaysarg** [comment]
You can initialize the library in your MainApplication.java as this:

new TwilioVoicePackage(false)

This way, the package will not require permissions, and then you can trigger them as @kevng9 says.

**Comment by jdegger** [comment]
This issue opens up the question if this repo should bother at all with permissions or just have React Native Permissions handle it. 

What do you guys propose?

**Comment by fmonsalvo** [comment]
We are using react-native-permissions to handle all the permissions our app needs, so I believe that in any application you will  need more than one permission and using one library to handle them all would be better than managing permission from each library that needs them. This results in using just one API to handle it, instead of learning an API per library.

**Comment by jdegger** [comment]
I agree, @fabriziomoscon, I propose we remove the permission flow in a next major upgrade.
