### ISSUE TITLE
iOS callkit screen disappears right after call accepted

### ISSUE THREAD

**Issue by kevng9** [hoxfon/react-native-twilio-programmable-voice#49]
Please include following information for better support

What version of React Native are you running? 0.48.2
What version of react-native-twilio-programmable-voice are you running? 3.2.0
What device are you using? (e.g iOS9 simulator, Android 6 device)? iOS11 device
Is your app running in foreground, background or not running? foreground
Is there any relevant message in the log? no
If using iOS, which pod version are you using? 'TwilioVoice', '=2.0.0-beta13'

Step to reproduce
1. Made call to device using TwilioVoice.connect({To:'user'});
2. Accepted call on user device callkit screen
3. call is active in background and application screen shows up. cannot switch to call screen

Hi All,

I'm having some trouble with managing the call once it's connected. After I accept the call on my screen, the call screen goes into the background and my app screen shows up. iOS shows me there is an active call and I can hear voices, but I cannot bring up the call screen to to hang up the call. Has anyone come across this or have any example code I can have a look at?

Thanks alot

**Comment by fecabianchi** [comment]
I'm facing the same issue, did you solve that?

**Comment by kevng9** [comment]
I still can't get the callkit screen to show. What I've done instead is create my own call screen and switch to it on the `connectionDidConnect` event.

**Comment by fecabianchi** [comment]
@fabriziomoscon can you help with this?

**Comment by fabriziomoscon** [comment]
Either Apple changed the way the incoming call is handled in ios11 or a past commit - following Twilio example - has changed this behaviour.
For sure now CallKit delegate control to the app when the call is accepted, so your app must listen to the `connectionDidConnect` event and display the appropriate screen.
