### ISSUE TITLE
Android Notification not triggered when app is closed / foreground

### ISSUE THREAD

**Issue by RUIFERNANDE5** [hoxfon/react-native-twilio-programmable-voice#50]
What version of React Native are you running? 0.49
What version of react-native-twilio-programmable-voice are you running? ^3.2.0
What device are you using? (e.g iOS9 simulator, Android 6 device)? Android 4,5,6 device

I'm currently using [react-native-fcm](https://github.com/evollu/react-native-fcm) for handling android notifications, the thing is.
I'm able to receive chat notifications (also from twilio services), I also receive notifications sent by the Firebase Console and I'm able to trigger voip notifications (using react-native-fcm listening events) when my app is either open or in foreground.
However, I'm not receiving any android push notification when the app is closed or in foregroud (as desired). Any clue whats the problem? 

P.S: I've correctly implemented this on iOS with callkit..

Thanks in advance.

**Comment by fabriziomoscon** [comment]
Hi, sorry for the delay in answering.
Have you implemented/installed the quickstart twilio android project and it shows the same problems.
Once that one works correctly there will be no or very few changes to use this library for your server.
Twilio can also provide better support on how to resolve this.

**Comment by RUIFERNANDE5** [comment]
Hey again, thanks for your response.
I already followed the quick start twilio voice for android with the same server and set of keys.
Everything works fine.
Now, analysing the native java code I found that the function `onMessageReceived` (VoiceFirebaseMessagingService.java) is not being triggered.
Not sure what to look for anymore.
Thanks in advance. Cheers

**Comment by fabriziomoscon** [comment]
Only two other things come to mind at this point:
- make sure your `manifest.xml` and services package name are the same as in the README
- make sure that your Push credentials stored on the account in the Twilio console are correct
