### ISSUE TITLE
Can't accept the call when device is locked

### ISSUE THREAD

**Issue by rochapablo** [hoxfon/react-native-twilio-programmable-voice#56]
What version of React Native are you running?
```0.48.4```

What version of react-native-twilio-programmable-voice are you running?
```3.7.0```

What device are you using? (e.g iOS9 simulator, Android 6 device)?
```Android 6.0.1 device```

Is your app running in foreground, background or not running?
```running in foreground and background```

Is there any relevant message in the log?
```No```

---

Well, I don't think this is an issue, but I'm here looking for ideas. The main issue is that when I receive the call while the device is locked, I don't have the accept button; I see the banner notification but without the accept/reject options.

Due this main issue, I'm trying to follow [this post](http://belka.us/en/callkit-android-react-native/), which gives the idea of build a native screen for Android *locked screen* cases.

I did not finish this task, but I already have done the screen and when the app it's open I'm able to send notification to the react-native. [You can see the code here](https://gist.github.com/rochapablo/8593cc418708ed93c96c5137d1729dea).

Another problem is, when I emit the ```handleIncomingCall``` my ```showUnlockScreen``` doesn't work, but if I change, removing ```handleIncomingCall```; the screen will be shown without  notification banner.

So my question is; do you have any idea about how create this screen keeping the current notification working?

**Comment by rochapablo** [comment]
Well, I changed the ```handleIncomingCall``` and now I got the sound

```
private void handleIncomingCall(...) {
        showUnlockScreen(context, callInvite);
        sendIncomingCallMessageToActivity(context, callInvite, notificationId);
        // showNotification(context, callInvite, notificationId, launchIntent);
```

I still having some others issues, which will be working on, but I believe that this could be add to the ```react-native-twilio-programmable-voice``` as a new feature.

**Comment by rochapablo** [comment]
@fabriziomoscon, have you hear about [ConnectionService](https://developer.android.com/reference/android/telecom/ConnectionService.html)?

**Comment by fabriziomoscon** [comment]
@rochapablo I have just saw ConnectionService now. It sounds like the way forward.
Also Hoxfon can't bypass the lock screen and a simple notification is displayed when there is an incoming call on screen lock... annoying.

**Comment by MarcoCanalcar** [comment]
@rochapablo Did you manage to get this working? I'm able to open the activity with the device locked but when the app is closed it opens and then closes in a second or so.

**Comment by rochapablo** [comment]
@MarcoCanalcar, try to follow the **UPDATE** part of https://stackoverflow.com/questions/48024740/android-activity-multiple-instance-resolved

This is probably get the right setup.

**Comment by rochapablo** [comment]
@fabriziomoscon, I tried _ConnectionService_, but was too much work since the documentation is... poor and examples are really hard to find. So I continue with the first idea to build my own screen.

**Comment by MarcoCanalcar** [comment]
@rochapablo Didn't work. When the app is running (either foreground/bacground), the activity opens properly over the locked phone, but when the app is not running and the phone is locked it opens and then closes. Do you have the same issue?

**Comment by cinder92** [comment]
any update on this?

**Comment by fabriziomoscon** [comment]
The new Android version i published after this post, allows the app to open the inbound call screen on full screen.
Did you guys tested that? I am using it on Android 8 and so far I haven't found major issues

**Comment by whitneywong** [comment]
@fabriziomoscon, when you say the update allows the app to open the inbound call screen on full screen, is the call screen you're referring to a screen written in javascript or one built using native code? i've been avoiding writing an Android screen for incoming calls, but it seems like that's a more full proof solution when the screen is locked.
