### ISSUE TITLE
Call not working after some period of time (iOS)

### ISSUE THREAD

**Issue by fecabianchi** [hoxfon/react-native-twilio-programmable-voice#64]
Please include following information for better support

What version of React Native are you running? **0.50.4**
What version of react-native-twilio-programmable-voice are you running? **3.5.0**
What device are you using? (e.g iOS9 simulator, Android 6 device)? **iOS 11 Device**
Is there any relevant message in the log? **No**
If using iOS, which pod version are you using? **3.10.0**

Step to reproduce

- When the app is reloaded, or resumed after a some period of time the call doesn't work, if i logout and login the voice call works again.

- Doesn't have the same issue with Android

**Comment by fecabianchi** [comment]
@fabriziomoscon have you seen this issue?

**Comment by fabriziomoscon** [comment]
When you resume the app you should really initialise the Twilio backend token, because it has an expiration.
Let me know if this fixes the problem.

**Comment by fecabianchi** [comment]
Ok, but if the app stays in the background the token will not be renewed right?

i saw two behaviors, so here is the scenario.
We have two users, if both have fresh login to the app the call works, if user1 (caller) get a fresh login and user2 doenst, the user1 hear the sound of calling on the phone but no notification arrives at user2, the twilio log when this happens is Incoming: Completed and Outgoing Dial: No Answer.

if the caller doesn't get a fresh login when he try to call there is no calling sound (completely mute) and nothing appears on the twilio logs.

**Comment by fabriziomoscon** [comment]
Please note that tokens needs to be valid ONLY for calling. Since you should only call in the foreground, initialising the token on each app resume ensure you have always a fresh session.
The library receives calls regardless of the backend token status.

**Comment by fecabianchi** [comment]
so there is some weird stuff going on because, if I get a valid token for calling the call works but the the receiver does not receive any call. so I'll investigate.

**Comment by eugenehp** [comment]
Hey @fecabianchi what's the update?
I'm seeing similar behaviour on my end as well.
Curious if you found some additional details after your investigation.

**Comment by fabriziomoscon** [comment]
@fecabianchi @eugenehp 
please update to
```
pod 'TwilioVoice', '=2.0.0-beta21'
```

and 
```
"react-native-twilio-programmable-voice": "^3.12.0",
```

and check if the problem persists

**Comment by eugenehp** [comment]
Nice job Fabrizio! I’ll check it ASAP and let you know.

**Comment by jpmermoz** [comment]
I'm getting the same issue. Incoming calls works great on background, but after a day my app stops receiving incoming calls unless I receive a new access-token from the server.

If I go to the Twilio debugger, i'm getting this error:

GCM/FCM client uninstalled or turned off notifications

This seems to happen on both Android and IOS.

**Comment by yatindma** [comment]
getting "Empty Credentials" when making a call from iOS or Viceversa, In Android it's working fine.

**Comment by jdegger** [comment]
Hi, since a long time has passed I will be closing this issue. Read our repository update in #158. I invite you to reopen this issue when you still have problems so we can debug the problems together.
