### ISSUE TITLE
TwilioVoice 2.0.1

### ISSUE THREAD

**Issue by eugenehp** [hoxfon/react-native-twilio-programmable-voice#66]
Hey guys, any plans to upgrade to new API structure?
Let me know if there is a roadmap so I can chip in with some contributions.

**Comment by fabriziomoscon** [comment]
Thanks for the offer @eugenehp . Any help is greatly appreciated!
The latest master uses https://www.twilio.com/docs/api/voice-sdk/ios/changelog#200-beta15-august-31-2017
and I haven't done any work to upgrade that.

Feel free to submit a PR with the API changes.
I try to keep up with Twilio as fast as I can, so I guess there isn't a real roadmap.

**Comment by fabriziomoscon** [comment]
@eugenehp I have created a PR #67 
It would be great if you could use those files to compile and test your app and give some feedback

**Comment by eugenehp** [comment]
Amazing, I’ll try it in my next build.

**Comment by fabriziomoscon** [comment]
v3.12.0 published on npm
