### ISSUE TITLE
deviceDidReceivedIncoming Event does not emmited

### ISSUE THREAD

**Issue by david-dss** [hoxfon/react-native-twilio-programmable-voice#70]
Please include following information for better support

What version of React Native are you running? 0.54.2
What version of react-native-twilio-programmable-voice are you running? 3.14
What device are you using? (e.g iOS9 simulator, Android 6 device)? Android 6 and 7.1 devices
Is your app running in foreground, background or not running? foreground
Is there any relevant message in the log? no
If using iOS, which pod version are you using?

Step to reproduce
- initialize each device/client with twilio token
- call connect() in one device and wait at the second device

Advanced:
Have you tried adding break point in native handlers and see the logs printed? yes, no log printed
can share a project with issue?
Did you try to reinstall the pods completely?

I've used the connect method to call another client, however the other client doesn't get deviceDidReceivedIncoming event

**Comment by fabriziomoscon** [comment]
Hi @david-dss,
the scenario you described as far as I am aware works and is a basic use case.
Could you check that the official Twilio Android quickstart project works with your server. Your server token, Twilio configurations, Google configurations should not be different, so if Twilio DEMO works we can narrow the issue down to this library.

**Comment by jdegger** [comment]
Hi, since a long time has passed I will be closing this issue. Read our repository update in #158. I invite you to reopen this issue when you still have problems so we can debug the problems together.

**Comment by vuvt** [comment]
Hi guys,
Could you help me to show me how can I get call_state when I accepted a call?
Thanks,
