### ISSUE TITLE
no "call in progress" notification on android 8

### ISSUE THREAD

**Issue by slootzky** [hoxfon/react-native-twilio-programmable-voice#71]
using RN-twilio-prog...voic version 3.7.3 , when running on a Samsung galaxy s7 device (with android 7) I see the "call in progress" notification.
when running same code on a google pixel XL (with android 8) I don't see this notification.

my target sdk : 23
when enabling the notification channel toast mode (developer options) I do see that my app tries to pop a notification of the channel "default"

**Comment by slootzky** [comment]
looks like this happens if you're not creating the channel prior to showing this notification.
this [PR](https://github.com/hoxfon/react-native-twilio-programmable-voice/pull/72) should fix it.

**Comment by fabriziomoscon** [comment]
the PR is merged
