### ISSUE TITLE
Let the client decide when to ask for microphone permissions

### ISSUE THREAD

**Issue by slootzky** [hoxfon/react-native-twilio-programmable-voice#74]
Hey , 
it's a good approach (product-wise) to ask users for permissions in the right context. [(a read for example)](https://uxplanet.org/mobile-ux-design-the-right-ways-to-ask-users-for-permissions-6cdd9ab25c27)
In our case the right context is when the user first tries to initiate a call but in the current design there's no way to do this. [we alwyas request it](https://github.com/hoxfon/react-native-twilio-programmable-voice/blob/master/android/src/main/java/com/hoxfon/react/RNTwilioVoice/TwilioVoiceModule.java#L163)

**Comment by slootzky** [comment]
a possible solution can be adding a `shouldAskForMicPermissions` flag to the [init method](https://github.com/hoxfon/react-native-twilio-programmable-voice/blob/6e220726d1d7f566d7d2c4bd2eab87872aaa6f3f/android/src/main/java/com/hoxfon/react/RNTwilioVoice/TwilioVoiceModule.java#L517)
with a default value of `true` , giving the clients the ability to decide if they want to ask for permissions by themselves

**Comment by slootzky** [comment]
@fabriziomoscon let me know what you think , and also if you want me to create such a PR?
Thanks :)

**Comment by slootzky** [comment]
well , I guess my case is more specific as my app only allows outgoing calls and can't receive calls.
I guess we can wait with initializing the library to the moment customer initiate a phone call.

still have to check that library initialization is idempotent , otherwise app should keep a special state for the library so it won't get initialized more than once.
in addition , need to check that it doesn't affects customer experience when initializing a phone.

**Comment by fabriziomoscon** [comment]
@slootzky as specified here:
https://github.com/twilio/voice-quickstart-android#managing-expiry
you can initialize the library before making each outbound call.

I think it is a good approach to add a parameter to the `init()` method so that library users can decide to opt out, extra checks must be put in place to stop calls when microphone permissions are not granted.

Feel free to send a PR.

**Comment by slootzky** [comment]
let me know what you think
