### ISSUE TITLE
Possible to Implement on Android w/o FCM/GCM?  

### ISSUE THREAD

**Issue by medelman17** [hoxfon/react-native-twilio-programmable-voice#86]
I just need the App to dial out one specific number--no incoming, no text, etc.,--is it possible to do this without implementing a Firebase App? Right now I'm getting `Default FirebaseApp is not initialized ... make sure to call FirebaseApp.initializeApp(context) first.`

**Comment by fabriziomoscon** [comment]
Theoretically it can be achieved. In practise, this lib need lots of work to made that possible.
1) research how to allow your app code to override: https://github.com/hoxfon/react-native-twilio-programmable-voice/blob/master/android/build.gradle
2) the main module needs to be c9mpletely rewritten to allow this specific configuration.

It might be easier to copy the relevant code into a new repo as an experiment. Than we can actually see how much of a difference there is.

**Comment by medelman17** [comment]
So, turns out, I just commented out the call to `registerForCallInvites()` in `initWithAccessToken` and appears to work like a charm. Any reason I should be weary of this approach

```
@ReactMethod
    public void initWithAccessToken(final String accessToken, Promise promise) {
        if (accessToken.equals("")) {
            promise.reject(new JSApplicationIllegalArgumentException("Invalid access token"));
            return;
        }

        TwilioVoiceModule.this.accessToken = accessToken;
        if (BuildConfig.DEBUG) {
            Log.d(TAG, "initWithAccessToken ACTION_FCM_TOKEN");
        }
        // registerForCallInvites();
        WritableMap params = Arguments.createMap();
        params.putBoolean("initialized", true);
        promise.resolve(params);
    }
```

**Comment by fabriziomoscon** [comment]
I guess that if you include firebase dependency you will eventually need to figure the Google service JSON file.
But I might be wrong.
If there is a way to have a clean solution that excludes all dependencies with FCM I would be happy to integrate into this library.
But I am not aware of such solution. We might seek help from the Android community

**Comment by jdegger** [comment]
For now, as this issue has further requests from others, I will be closing it. It seems like adding support for 'outgoing call only' is not requested a lot so we marked it as outside the scope of this repo.

Read our repository update in #158. I invite you to reopen this issue when you still have problems so we can debug the problems together.
