### ISSUE TITLE
More than one FirebaseMessagingService subclass

### ISSUE THREAD

**Issue by mahyarr** [hoxfon/react-native-twilio-programmable-voice#88]
Hi and thanks for this great library.

I'm in the process of integrating RNProgrammableVoice into my project but I hit a roadblock.

I'm currently using another library (RNFirebase) that also depends on FirebaseMessagingService. Adding the <service> tags to my AndroidManifest.xml causes only one of these subclasses to get called.

What's a good way to handle two libraries that both need to listen to Firebase messages?

**Comment by langan** [comment]
HI @mahyarr I am having the same issue, did you manage to solve this?
