### ISSUE TITLE
Remove 'client:' from Callkit incoming call handle

### ISSUE THREAD

**Issue by TheRohitSharma** [hoxfon/react-native-twilio-programmable-voice#89]
Is there any way to remove the 'client:' from the Callkit incoming call handle? I know twiML requires it, but i've found that I can strip it in the code by doing this:

`- (void)reportIncomingCallFrom:(NSString *)from withUUID:(NSUUID *)uuid {
  NSString *_from = from;
  _from  = [_from stringByReplacingOccurrencesOfString:@"client:" withString:@""];
{...}
`

Of course, I don't want to edit this library directly, and as I have no objective-c experience, I wouldn't know where to begin with a PR. Are there any solutions for this?

**Comment by fabriziomoscon** [comment]
@TheRohitSharma this sounds like a quick win.
Just so I understand 100% what are you trying to achieve do you have images/gif demo to show the issue? If that it easy I can code it up for you

**Comment by TheRohitSharma** [comment]
@fabriziomoscon I have an image here. 

![image uploaded from ios](https://user-images.githubusercontent.com/9807835/40748651-b835bf38-6426-11e8-8e50-a6808144e2a2.png)

Twilio requires 'client:' infront of the caller_id value, otherwise it converts the string to a number. Without 'client:', 'Bob' would just be three numbers. Is there any way, without modifying the original library, to strip 'client:' out of the 'from' value in reportIncomingCallFrom? Maybe I can make a separate class?

**Comment by nxz91** [comment]
Hi guys, I need both  the id of the caller and a friendly name at the same time. I'm worked around this topic in two ways now:

- I am sending a base32 encrypted from value (replacing = and I think 1 with something that is supported by Twilio's policy) that is essentially a JSON object. These from values are allowed to become really long on Twilio's side but should not contain certain characters.
- I am then decoding these strings on the client side before passing them to CallKit. I was too lazy to do the same on Android and am now just using a hardcoded easily readable value there (the app name). I will replicate iOS asap.

On iOS I used this library for base32 decoding: https://github.com/ekscrypto/Base32

Cheers
Leonard

**Comment by jdegger** [comment]
@nxz91 Are you willing to provide this as an PR?

**Comment by jdegger** [comment]
As per PR https://github.com/hoxfon/react-native-twilio-programmable-voice/pull/170 I have now marked this issue as `In Progress`.

**Comment by jdegger** [comment]
This issue has been resolved.

Published on NPM react-native-twilio-programmable-voice@4.2.0

Thank you @dakenf
