### ISSUE TITLE
Make call between SIP credentials of SIP Domain

### ISSUE THREAD

**Issue by hnq90** [hoxfon/react-native-twilio-programmable-voice#90]
I created a SIP Domain with some SIP credentials. So how can I make call between my sip credentials?
Here's the console: https://www.twilio.com/console/voice/sip/endpoints/

**Comment by fabriziomoscon** [comment]
I think this question would be better answered by the Twilio support

**Comment by jdegger** [comment]
Hi, since a long time has passed I will be closing this issue. Read our repository update in #158. I invite you to reopen this issue when you still have problems so we can debug the problems together.
