### ISSUE TITLE
No events where triggering ie: deviceReady, deviceNotReady

### ISSUE THREAD

**Issue by dMuruGit** [hoxfon/react-native-twilio-programmable-voice#92]
1. Started react native project with react-native init
2. Installed react-native-twilio-programmable-voice and linked
3. init pod and installed pod with the instructions given in doc
4. imported package in app.js
5.  TwilioVoice.initWithToken(accessToken)

Now trying to trigger the events

```
TwilioVoice.addEventListener('deviceReady', function () {
      alert('deviceReady')
})
TwilioVoice.addEventListener('deviceNotReady', function (data) {
     alert('deviceNotReady')
})
```

But no events where triggering...

**Comment by nxz91** [comment]
They are not firing in the simulator for me, on an actual device they do. Are you using the simulator?

**Comment by kukadiyaAni** [comment]
@nxz91 I have a checked on the live device as well but still not trigger any event in iOS,

Thanks in Advance!

**Comment by thanhnvpk01168** [comment]
@kukadiyaAni ku
have you fixed it, I have the same error as you, can you share more information, thanks.

**Comment by skjangid** [comment]
@thanhnvpk01168 
How you fix?  i have same issue with me, not trigger any event in iOS but its working fine in android.
