### ISSUE TITLE
Can I remove the CallKit screen? (iOS)

### ISSUE THREAD

**Issue by huunovahub** [hoxfon/react-native-twilio-programmable-voice#93]
I don't want to use the CallKit of ios, so can I remove the callkit screen?

**Comment by MAYANK4482** [comment]
hi please provide code about  simple call in React Native (Twilio)
Because I facing many problems from Twilio integration 
:- vadaliyamayank3@gmail.com

**Comment by jdegger** [comment]
Closing this issue as it has been answered
