### ISSUE TITLE
TwilioVoice.disconnect() does nothing on Android

### ISSUE THREAD

**Issue by nxz91** [hoxfon/react-native-twilio-programmable-voice#98]
Hi again,

While this is working on iOS, .disconnect() does not disconnect the call on Android. Any ideas why?

Thanks!
Leonard

**Comment by edzh1** [comment]
@nxz91 Hello. Can you, please, provide some additional info/code?

**Comment by sa7bi** [comment]
The same for me. With iOS the `connectionDidDisconnect` event is fired but not for Android, which is weird !

**Comment by gentleShark** [comment]
it does seem to terminate the call but does not play a tone (at least on Android) to indicate to the caller that the connection has been disconnected.

**Comment by MAYANK4482** [comment]
> @nxz91 Hello. Please, provide some additional info/code

hi please provide code about  simple call in React Native (Twilio)
Because I facing many problems from Twilio integration 
:- vadaliyamayank3@gmail.com

**Comment by jdegger** [comment]
Hi, since a long time has passed I will be closing this issue. Read our repository update in #158. I invite you to reopen this issue when you still have problems so we can debug the problems together.
